# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Provice.create(:id => 1, :name => '北京市')
Provice.create(:id => 2, :name => '天津市')
Provice.create(:id => 3, :name => '上海市')
Provice.create(:id => 4, :name => '重庆市')
Provice.create(:id => 5, :name => '河北省')
Provice.create(:id => 6, :name => '山西省')
Provice.create(:id => 7, :name => '台湾省')
Provice.create(:id => 8, :name => '辽宁省')
Provice.create(:id => 9, :name => '吉林省')
Provice.create(:id => 10, :name => '黑龙江省')
Provice.create(:id => 11, :name => '江苏省')
Provice.create(:id => 12, :name => '浙江省')
Provice.create(:id => 13, :name => '安徽省')
Provice.create(:id => 14, :name => '福建省')
Provice.create(:id => 15, :name => '江西省')
Provice.create(:id => 16, :name => '山东省')
Provice.create(:id => 17, :name => '河南省')
Provice.create(:id => 18, :name => '湖北省')
Provice.create(:id => 19, :name => '湖南省')
Provice.create(:id => 20, :name => '广东省')
Provice.create(:id => 21, :name => '甘肃省')
Provice.create(:id => 22, :name => '四川省')
Provice.create(:id => 23, :name => '贵州省')
Provice.create(:id => 24, :name => '海南省')
Provice.create(:id => 25, :name => '云南省')
Provice.create(:id => 26, :name => '青海省')
Provice.create(:id => 27, :name => '陕西省')
Provice.create(:id => 28, :name => '广西壮族自治区')
Provice.create(:id => 29, :name => '西藏自治区')
Provice.create(:id => 30, :name => '宁夏回族自治区')
Provice.create(:id => 31, :name => '新疆维吾尔自治区')
Provice.create(:id => 32, :name => '内蒙古自治区')
Provice.create(:id => 33, :name => '澳门特别行政区')
Provice.create(:id => 34, :name => '香港特别行政区')
