# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Province.create(id: 1, name: '北京市')
Province.create(id: 2, name: '天津市')
Province.create(id: 3, name: '上海市')
Province.create(id: 4, name: '重庆市')
Province.create(id: 5, name: '河北省')
Province.create(id: 6, name: '山西省')
Province.create(id: 7, name: '台湾省')
Province.create(id: 8, name: '辽宁省')
Province.create(id: 9, name: '吉林省')
Province.create(id: 10, name: '黑龙江省')
Province.create(id: 11, name: '江苏省')
Province.create(id: 12, name: '浙江省')
Province.create(id: 13, name: '安徽省')
Province.create(id: 14, name: '福建省')
Province.create(id: 15, name: '江西省')
Province.create(id: 16, name: '山东省')
Province.create(id: 17, name: '河南省')
Province.create(id: 18, name: '湖北省')
Province.create(id: 19, name: '湖南省')
Province.create(id: 20, name: '广东省')
Province.create(id: 21, name: '甘肃省')
Province.create(id: 22, name: '四川省')
Province.create(id: 23, name: '贵州省')
Province.create(id: 24, name: '海南省')
Province.create(id: 25, name: '云南省')
Province.create(id: 26, name: '青海省')
Province.create(id: 27, name: '陕西省')
Province.create(id: 28, name: '广西壮族自治区')
Province.create(id: 29, name: '西藏自治区')
Province.create(id: 30, name: '宁夏回族自治区')
Province.create(id: 31, name: '新疆维吾尔自治区')
Province.create(id: 32, name: '内蒙古自治区')
Province.create(id: 33, name: '澳门特别行政区')
Province.create(id: 34, name: '香港特别行政区')

